language: ruby
cache: bundler
dist: xenial

branches:
  only:
  - master

matrix:
  include:
    - rvm: 2.4.9
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: 2.7.0
    - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
